spring:
    application:
        name: instaclone
        description: Instagram Clone
    data:
        mongodb:
            host: 127.0.0.1
            port: 27017
            database: instaclone

cors:
    allowed-origins: http://localhost:8080, http://localhost:3000
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    allowed-headers: "*"
    allow-credentials: true

server:
    port: 8080
